# Generated by Django 4.2.1 on 2024-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='photo',
            field=models.ImageField(default=True, upload_to='images/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
