# Generated by Django 4.2.1 on 2024-12-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='purchase',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='coffee.ingredient'),
        ),
    ]
