# Generated by Django 4.2.1 on 2024-12-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_remove_purchase_purchase_date_purchase_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineadmin',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='MachineAdmin',
        ),
    ]
